# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required version of the configuration format
version: 2

# Set the OS, Python version, and other tools you might need for the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"  # Specify the Python version to use

# Configure Sphinx for building the documentation
sphinx:
  configuration: source/conf.py  # Path to your Sphinx configuration file

# Optionally build your docs in additional formats such as PDF and ePub
formats:
# - pdf  
  - epub  

# Specify the Python dependencies required to build your documentation
python:
  install:
    - requirements: requirements.txt  # Path to the requirements.txt file in your repository
